import { Room } from "@/models/Room";

export const roomsMockResponse: Room[] = [
  {
    code: "ROOM1",
    label: "Votación Familiar",
    description: "Decidimos el destino de las vacaciones familiares",
    ownerUserId: 1,
    isPrivate: false,
    memberCount: 5,
    lastActivity: "hace 2h",
    status: "active",
    hasUnreadVotes: true,
  },
  {
    code: "WORK2",
    label: "Reunión de Trabajo",
    description: "Votaciones sobre el nuevo proyecto de la empresa",
    ownerUserId: 2,
    isPrivate: false,
    memberCount: 12,
    lastActivity: "hace 1d",
    status: "active",
    hasUnreadVotes: false,
  },
  {
    code: "PARTY",
    label: "Fiesta de Cumpleaños",
    description: "Elegimos tema y decoración para la fiesta",
    ownerUserId: 1,
    isPrivate: true,
    memberCount: 8,
    lastActivity: "hace 3d",
    status: "finished",
    hasUnreadVotes: false,
    key: "PARTY123",
  },
  {
    code: "TRIP",
    label: "Viaje con Amigos",
    description: "Decidimos el destino y actividades del viaje",
    ownerUserId: 4,
    isPrivate: false,
    memberCount: 4,
    lastActivity: "hace 1w",
    status: "active",
    hasUnreadVotes: true,
  },
  {
    code: "BOOKCLUB",
    label: "Club de Lectura",
    description: "Discutimos sobre los libros que estamos leyendo",
    ownerUserId: 1,
    isPrivate: true,
    memberCount: 6,
    lastActivity: "hace 2d",
    status: "active",
    hasUnreadVotes: false,
    key: "BOOKCLUB123",
  },
  {
    code: "GAMENIGHT",
    label: "Noche de Juegos",
    description: "Organizamos una noche de juegos de mesa",
    ownerUserId: 6,
    isPrivate: false,
    memberCount: 5,
    lastActivity: "hace 1d",
    status: "active",
    hasUnreadVotes: true,
  },
  {
    code: "COMMUNITY",
    label: "Reunión Comunitaria",
    description: "Discutimos temas de interés para la comunidad",
    ownerUserId: 1,
    isPrivate: false,
    memberCount: 10,
    lastActivity: "hace 2h",
    status: "active",
    hasUnreadVotes: false,
  },
];
