import { Room } from "@/models/Room";

export const roomsMockResponse: Room[] = [
  {
    code: "ROOM1",
    label: "Votación Familiar",
    description: "Decidimos el destino de las vacaciones familiares",
    ownerUserId: 1,
    ownerName: "Alice Smith",
    memberCount: 5,
    lastActivity: "hace 2h",
    status: "active",
    hasUnreadVotes: true,
    tags: ["familia", "vacaciones"],
    scope: {
      isPrivate: false,
      membersType: "unrestricted",
    },
  },
  {
    code: "WORK2",
    label: "Reunión de Trabajo",
    description: "Votaciones sobre el nuevo proyecto de la empresa",
    ownerUserId: 2,
    ownerName: "Bob Johnson",
    memberCount: 8,
    lastActivity: "hace 1d",
    status: "active",
    hasUnreadVotes: false,
    tags: ["trabajo", "proyecto"],
    scope: {
      isPrivate: false,
      membersType: "unrestricted",
    },
  },
  {
    code: "PARTY",
    label: "Fiesta de Cumpleaños",
    description: "Elegimos tema y decoración para la fiesta",
    ownerUserId: 3,
    ownerName: "Charlie Brown",
    memberCount: 6,
    lastActivity: "hace 3d",
    status: "finished",
    hasUnreadVotes: false,
    tags: ["fiesta", "cumpleaños"],
    scope: {
      isPrivate: true,
      membersType: "authenticated",
      key: "PARTY123",
    },
  },
  {
    code: "TRIP",
    label: "Viaje con Amigos",
    description: "Decidimos el destino y actividades del viaje",
    ownerUserId: 4,
    ownerName: "Diana Prince",
    memberCount: 4,
    lastActivity: "hace 1w",
    status: "active",
    hasUnreadVotes: true,
    tags: ["viaje", "amigos"],
    scope: {
      isPrivate: false,
      membersType: "unrestricted",
    },
  },
  {
    code: "BOOKCLUB",
    label: "Club de Lectura",
    description: "Discutimos sobre los libros que estamos leyendo",
    ownerUserId: 5,
    ownerName: "Ethan Hunt",
    memberCount: 5,
    lastActivity: "hace 2d",
    status: "active",
    hasUnreadVotes: false,
    tags: ["libros", "lectura"],
    scope: {
      isPrivate: true,
      membersType: "unrestricted",
      key: "BOOKCLUB123",
    },
  },
  {
    code: "GAMENIGHT",
    label: "Noche de Juegos",
    description: "Organizamos una noche de juegos de mesa",
    ownerUserId: 6,
    ownerName: "Fiona Gallagher",
    memberCount: 5,
    lastActivity: "hace 1d",
    status: "active",
    hasUnreadVotes: true,
    tags: ["juegos", "diversión"],
    scope: {
      isPrivate: false,
      membersType: "unrestricted",
    },
  },
  {
    code: "COMMUNITY",
    label: "Reunión Comunitaria",
    description: "Discutimos temas de interés para la comunidad",
    ownerUserId: 7,
    ownerName: "George Martin",
    memberCount: 9,
    lastActivity: "hace 2h",
    status: "active",
    hasUnreadVotes: false,
    tags: ["comunidad", "reunión"],
    scope: {
      isPrivate: false,
      membersType: "unrestricted",
    },
  },
  {
    code: "STUDY",
    label: "Grupo de Estudio",
    description: "Coordinamos sesiones de estudio para exámenes finales",
    ownerUserId: 2,
    ownerName: "Bob Johnson",
    memberCount: 7,
    lastActivity: "hace 4h",
    status: "active",
    hasUnreadVotes: true,
    tags: ["estudio", "exámenes"],
    scope: {
      isPrivate: true,
      membersType: "authenticated",
      key: "STUDY456",
    },
  },
  {
    code: "MOVIE",
    label: "Noche de Películas",
    description: "Elegimos qué película ver este fin de semana",
    ownerUserId: 8,
    ownerName: "Helena Martinez",
    memberCount: 3,
    lastActivity: "hace 6h",
    status: "active",
    hasUnreadVotes: false,
    tags: ["películas", "entretenimiento"],
    scope: {
      isPrivate: false,
      membersType: "unrestricted",
    },
  },
  {
    code: "FITNESS",
    label: "Rutina de Ejercicios",
    description: "Decidimos los horarios y actividades del gimnasio",
    ownerUserId: 4,
    ownerName: "Diana Prince",
    memberCount: 6,
    lastActivity: "hace 12h",
    status: "active",
    hasUnreadVotes: true,
    tags: ["fitness", "salud"],
    scope: {
      isPrivate: false,
      membersType: "unrestricted",
    },
  },
  {
    code: "MUSIC",
    label: "Festival de Música",
    description: "Organizamos un evento musical para la universidad",
    ownerUserId: 9,
    ownerName: "Ivan Rodriguez",
    memberCount: 12,
    lastActivity: "hace 5h",
    status: "active",
    hasUnreadVotes: false,
    tags: ["música", "evento"],
    scope: {
      isPrivate: true,
      membersType: "authenticated",
      key: "MUSIC789",
    },
  },
  {
    code: "COOKING",
    label: "Clase de Cocina",
    description: "Decidimos el menú para el taller de cocina",
    ownerUserId: 1,
    ownerName: "Alice Smith",
    memberCount: 8,
    lastActivity: "hace 1d",
    status: "finished",
    hasUnreadVotes: false,
    tags: ["cocina", "gastronomía"],
    scope: {
      isPrivate: false,
      membersType: "unrestricted",
    },
  },
  {
    code: "SPORTS",
    label: "Torneo de Fútbol",
    description: "Organizamos los equipos y horarios del torneo",
    ownerUserId: 10,
    ownerName: "Julia Torres",
    memberCount: 16,
    lastActivity: "hace 30m",
    status: "active",
    hasUnreadVotes: true,
    tags: ["deportes", "fútbol"],
    scope: {
      isPrivate: false,
      membersType: "unrestricted",
    },
  },
  {
    code: "TECH",
    label: "Meetup de Tecnología",
    description: "Discutimos las últimas tendencias en desarrollo",
    ownerUserId: 5,
    ownerName: "Ethan Hunt",
    memberCount: 15,
    lastActivity: "hace 3h",
    status: "active",
    hasUnreadVotes: true,
    tags: ["tecnología", "programación"],
    scope: {
      isPrivate: true,
      membersType: "authenticated",
      key: "TECH999",
    },
  },
  {
    code: "ART",
    label: "Taller de Arte",
    description: "Elegimos los materiales para el próximo proyecto",
    ownerUserId: 11,
    ownerName: "Kevin López",
    memberCount: 5,
    lastActivity: "hace 2d",
    status: "active",
    hasUnreadVotes: false,
    tags: ["arte", "creatividad"],
    scope: {
      isPrivate: false,
      membersType: "unrestricted",
    },
  },
  {
    code: "VOLUNTEER",
    label: "Voluntariado",
    description: "Coordinamos actividades de ayuda social",
    ownerUserId: 3,
    ownerName: "Charlie Brown",
    memberCount: 9,
    lastActivity: "hace 8h",
    status: "active",
    hasUnreadVotes: true,
    tags: ["voluntariado", "social"],
    scope: {
      isPrivate: false,
      membersType: "unrestricted",
    },
  },
];
