import { Room } from "@/models/Room";

export const roomsMockResponse: Room[] = [
  {
    code: "ROOM1",
    label: "Votación Familiar",
    description: "Decidimos el destino de las vacaciones familiares",
    ownerUserId: 1,
    ownerName: "Alice Smith",
    memberCount: 5,
    lastActivity: "hace 2h",
    status: "active",
    hasUnreadVotes: true,
    tags: ["familia", "vacaciones"],
    scope: {
      isPrivate: false,
      membersType: "unrestricted",
    },
  },
  {
    code: "WORK2",
    label: "Reunión de Trabajo",
    description: "Votaciones sobre el nuevo proyecto de la empresa",
    ownerUserId: 2,
    ownerName: "Bob Johnson",
    memberCount: 8,
    lastActivity: "hace 1d",
    status: "active",
    hasUnreadVotes: false,
    tags: ["trabajo", "proyecto"],
    scope: {
      isPrivate: false,
      membersType: "unrestricted",
    },
  },
  {
    code: "PARTY",
    label: "Fiesta de Cumpleaños",
    description: "Elegimos tema y decoración para la fiesta",
    ownerUserId: 3,
    ownerName: "Charlie Brown",
    memberCount: 6,
    lastActivity: "hace 3d",
    status: "finished",
    hasUnreadVotes: false,
    tags: ["fiesta", "cumpleaños"],
    scope: {
      isPrivate: true,
      membersType: "authenticated",
      key: "PARTY123",
    },
  },
  {
    code: "TRIP",
    label: "Viaje con Amigos",
    description: "Decidimos el destino y actividades del viaje",
    ownerUserId: 4,
    ownerName: "Diana Prince",
    memberCount: 4,
    lastActivity: "hace 1w",
    status: "active",
    hasUnreadVotes: true,
    tags: ["viaje", "amigos"],
    scope: {
      isPrivate: false,
      membersType: "unrestricted",
    },
  },
  {
    code: "BOOKCLUB",
    label: "Club de Lectura",
    description: "Discutimos sobre los libros que estamos leyendo",
    ownerUserId: 5,
    ownerName: "Ethan Hunt",
    memberCount: 5,
    lastActivity: "hace 2d",
    status: "active",
    hasUnreadVotes: false,
    tags: ["libros", "lectura"],
    scope: {
      isPrivate: true,
      membersType: "unrestricted",
      key: "BOOKCLUB123",
    },
  },
  {
    code: "GAMENIGHT",
    label: "Noche de Juegos",
    description: "Organizamos una noche de juegos de mesa",
    ownerUserId: 6,
    ownerName: "Fiona Gallagher",
    memberCount: 5,
    lastActivity: "hace 1d",
    status: "active",
    hasUnreadVotes: true,
    tags: ["juegos", "diversión"],
    scope: {
      isPrivate: false,
      membersType: "unrestricted",
    },
  },
  {
    code: "COMMUNITY",
    label: "Reunión Comunitaria",
    description: "Discutimos temas de interés para la comunidad",
    ownerUserId: 7,
    ownerName: "George Martin",
    memberCount: 9,
    lastActivity: "hace 2h",
    status: "active",
    hasUnreadVotes: false,
    tags: ["comunidad", "reunión"],
    scope: {
      isPrivate: false,
      membersType: "unrestricted",
    },
  },
];
