import { User } from "@/models/User";

export const USER_MOCK_RESPONSE: User[] = [
  {
    id: 1,
    userName: "Alice",
    email: "alice@example.com",
    password: "q",
    type: "email",
  },
  {
    id: 2,
    userName: "Bob",
    email: "bob@example.com",
    password: "q",
    type: "email",
  },
  {
    id: 3,
    userName: "Charlie",
    email: "charlie@example.com",
    password: "q",
    type: "email",
  },
  {
    id: 4,
    userName: "Diana",
    email: "diana@example.com",
    password: "q",
    type: "email",
  },
  {
    id: 5,
    userName: "Ethan",
    email: "ethan@example.com",
    password: "q",
    type: "email",
  },
  {
    id: 6,
    userName: "Fiona",
    email: "fiona@example.com",
    password: "q",
    type: "email",
  },
  {
    id: 7,
    userName: "George",
    email: "george@example.com",
    password: "q",
    type: "email",
  },
  {
    id: 8,
    userName: "Hannah",
    email: "hannah@example.com",
    password: "q",
    type: "email",
  },
  {
    id: 9,
    userName: "Ian",
    email: "ian@example.com",
    password: "q",
    type: "email",
  },
  {
    id: 10,
    userName: "Julia",
    email: "julia@example.com",
    password: "q",
    type: "email",
  },
  {
    id: 11,
    userName: "Kevin",
    email: "kevin@example.com",
    password: "q",
    type: "email",
  },
  {
    id: 12,
    userName: "Laura",
    email: "laura@example.com",
    password: "q",
    type: "email",
  },
  {
    id: 13,
    userName: "Michael",
    email: "michael@example.com",
    password: "q",
    type: "email",
  },
  {
    id: 14,
    userName: "Nina",
    email: "nina@example.com",
    password: "q",
    type: "email",
  },
  {
    id: 15,
    userName: "Oscar",
    email: "oscar@example.com",
    password: "q",
    type: "email",
  },
  {
    id: 16,
    userName: "Paul",
    email: "paul@example.com",
    password: "q",
    type: "email",
  },
  {
    id: 17,
    userName: "Quinn",
    email: "quinn@example.com",
    password: "q",
    type: "email",
  },
  {
    id: 18,
    userName: "Rachel",
    email: "rachel@example.com",
    password: "q",
    type: "email",
  },
  {
    id: 19,
    userName: "Steve",
    email: "steve@example.com",
    password: "q",
    type: "email",
  },
  {
    id: 20,
    userName: "Tina",
    email: "tina@example.com",
    password: "q",
    type: "email",
  },
  {
    id: 21,
    userName: "Uma",
    email: "uma@example.com",
    password: "q",
    type: "email",
  },
  {
    id: 22,
    userName: "Victor",
    email: "victor@example.com",
    password: "q",
    type: "email",
  },
  {
    id: 23,
    userName: "Wendy",
    email: "wendy@example.com",
    password: "q",
    type: "email",
  },
  {
    id: 24,
    userName: "Xander",
    email: "xander@example.com",
    password: "q",
    type: "email",
  },
];
